<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class datospen extends Model
{
    protected $table = 'datospen';
    public $timestamps = false;
    protected $fillable = [
        'num_pen',
        'u_version',
        'rfc_pen',
        'curp',
        'num_issste',
        'nombre',
        'paterno',
        'materno',
        'nombre_h',
        'ind_nomb',
        'sexo',
        'tip_pen_act',
        'tip_pen_org',
        'tip_pago',
        'ent_pago',
        'zon_pago',
        'ent_pen',
        'primer_ramo',
        'primera_fecha',
        'ult_ramo',
        'ult_fecha',
        'sueldo_reg',
        'procentaje',
        'imp_ori_pendi',
        'imp_ori_pende',
        'fecha_inidi',
        'fecha_inide',
        'tiempo_serv_trab',
        'num_deudo',
        'grupo_familiar',
        'vigencia',
        'fecha_vigencia',
        'alta_nomina',
        'importe_pen',
        'radicacion_exp',
        'num_cheque',
        'total_percep',
        'total_deduc',
        'liquido',
        'nombre_cheque',
        'meses_cotizados',
        'meses_nocotizados',
        'meses_pagados',
        'plazas',
        'ind_at_dir',
        'cta_at_dir',
        'fecha_reval',
        'spe_id',
        'ptg_aumen',
        'cuota_ant',
        'ramo1',
        'clave1',
        'nivel1',
        'ptje1',
        'estatus1',
        'ramo2',
        'clave2',
        'nivel2',
        'ptje2',
        'estatus2',
        'ramo3',
        'clave3',
        'nivel3',
        'ptje3',
        'estatus3',
        'ramo4',
        'clave4',
        'nivel4',
        'ptje4',
        'estatus4',
        'ramo5',
        'clave5',
        'nivel5',
        'ptje5',
        'estatus5',
    ];
}
